export const imgs = {
    en: 'assets/imgs/template/en.svg',
    fr: 'assets/imgs/template/flag-fr.svg',
    es: 'assets/imgs/template/flag-es.svg',
    pt: 'assets/imgs/template/flag-pt.svg',
    cn: 'assets/imgs/template/flag-cn.svg',
    usd: 'assets/imgs/template/en.svg',
    logo: 'assets/imgs/template/logo.svg',
    sp5: 'assets/imgs/page/homepage1/imgsp5.png',
    sp4: 'assets/imgs/page/homepage1/imgsp4.png',
    appstore: 'assets/imgs/template/appstore.png',
    ggPlay: 'assets/imgs/template/google-play.png',
    payment: 'assets/imgs/template/payment-method.png',
    logo2: 'assets/imgs/template/logo-2.svg',
    amazon: 'assets/imgs/page/account/amazon.svg',
    google: 'assets/imgs/page/account/google.svg',
    meo: 'assets/imgs/template/meo.jpg',
    hotel: 'assets/imgs/template/hotel.jpg',
  };
  export default imgs;